export const CHAMPIONS = [
  { id: "Aatrox", name: "Aatrox", roles: ["Top"] },
  { id: "Ahri", name: "Ahri", roles: ["Mid"] },
  { id: "Akali", name: "Akali", roles: ["Mid", "Top"] },
  { id: "Alistar", name: "Alistar", roles: ["Support"] },
  { id: "Amumu", name: "Amumu", roles: ["Jungle", "Support"] },
  { id: "Anivia", name: "Anivia", roles: ["Mid"] },
  { id: "Annie", name: "Annie", roles: ["Mid", "Support"] },
  { id: "Aphelios", name: "Aphelios", roles: ["Bot"] },
  { id: "Ashe", name: "Ashe", roles: ["Bot", "Support"] },
  { id: "AurelionSol", name: "Aurelion Sol", roles: ["Mid"] },
  { id: "Azir", name: "Azir", roles: ["Mid"] },
  { id: "Bard", name: "Bard", roles: ["Support"] },
  { id: "Belveth", name: "Bel'Veth", roles: ["Jungle"] },
  { id: "Blitzcrank", name: "Blitzcrank", roles: ["Support"] },
  { id: "Brand", name: "Brand", roles: ["Support", "Jungle", "Mid"] },
  { id: "Braum", name: "Braum", roles: ["Support"] },
  { id: "Briar", name: "Briar", roles: ["Jungle"] },
  { id: "Caitlyn", name: "Caitlyn", roles: ["Bot"] },
  { id: "Camille", name: "Camille", roles: ["Top", "Support"] },
  { id: "Cassiopeia", name: "Cassiopeia", roles: ["Mid", "Top"] },
  { id: "Chogath", name: "Cho'Gath", roles: ["Top", "Mid"] },
  { id: "Corki", name: "Corki", roles: ["Bot", "Mid"] },
  { id: "Darius", name: "Darius", roles: ["Top"] },
  { id: "Diana", name: "Diana", roles: ["Jungle", "Mid"] },
  { id: "DrMundo", name: "Dr. Mundo", roles: ["Top", "Jungle"] },
  { id: "Draven", name: "Draven", roles: ["Bot"] },
  { id: "Ekko", name: "Ekko", roles: ["Jungle", "Mid"] },
  { id: "Elise", name: "Elise", roles: ["Jungle"] },
  { id: "Evelynn", name: "Evelynn", roles: ["Jungle"] },
  { id: "Ezreal", name: "Ezreal", roles: ["Bot"] },
  { id: "Fiddlesticks", name: "Fiddlesticks", roles: ["Jungle", "Support"] },
  { id: "Fiora", name: "Fiora", roles: ["Top"] },
  { id: "Fizz", name: "Fizz", roles: ["Mid"] },
  { id: "Galio", name: "Galio", roles: ["Mid", "Support"] },
  { id: "Gangplank", name: "Gangplank", roles: ["Top", "Mid"] },
  { id: "Garen", name: "Garen", roles: ["Top"] },
  { id: "Gnar", name: "Gnar", roles: ["Top"] },
  { id: "Gragas", name: "Gragas", roles: ["Jungle", "Top", "Mid"] },
  { id: "Graves", name: "Graves", roles: ["Jungle"] },
  { id: "Gwen", name: "Gwen", roles: ["Top", "Jungle"] },
  { id: "Hecarim", name: "Hecarim", roles: ["Jungle"] },
  { id: "Heimerdinger", name: "Heimerdinger", roles: ["Top", "Mid", "Support"] },
  { id: "Hwei", name: "Hwei", roles: ["Mid", "Support"] },
  { id: "Illaoi", name: "Illaoi", roles: ["Top"] },
  { id: "Irelia", name: "Irelia", roles: ["Top", "Mid"] },
  { id: "Ivern", name: "Ivern", roles: ["Jungle", "Support"] },
  { id: "Janna", name: "Janna", roles: ["Support"] },
  { id: "JarvanIV", name: "Jarvan IV", roles: ["Jungle"] },
  { id: "Jax", name: "Jax", roles: ["Top", "Jungle"] },
  { id: "Jayce", name: "Jayce", roles: ["Top", "Mid"] },
  { id: "Jhin", name: "Jhin", roles: ["Bot"] },
  { id: "Jinx", name: "Jinx", roles: ["Bot"] },
  { id: "Kaisa", name: "Kai'Sa", roles: ["Bot"] },
  { id: "Kalista", name: "Kalista", roles: ["Bot"] },
  { id: "Karma", name: "Karma", roles: ["Support", "Mid"] },
  { id: "Karthus", name: "Karthus", roles: ["Jungle", "Bot"] },
  { id: "Kassadin", name: "Kassadin", roles: ["Mid"] },
  { id: "Katarina", name: "Katarina", roles: ["Mid"] },
  { id: "Kayle", name: "Kayle", roles: ["Top", "Mid"] },
  { id: "Kayn", name: "Kayn", roles: ["Jungle"] },
  { id: "Kennen", name: "Kennen", roles: ["Top", "Mid"] },
  { id: "Khazix", name: "Kha'Zix", roles: ["Jungle"] },
  { id: "Kindred", name: "Kindred", roles: ["Jungle"] },
  { id: "Kled", name: "Kled", roles: ["Top", "Mid"] },
  { id: "KogMaw", name: "Kog'Maw", roles: ["Bot", "Mid"] },
  { id: "KSante", name: "K'Sante", roles: ["Top"] },
  { id: "Leblanc", name: "LeBlanc", roles: ["Mid"] },
  { id: "LeeSin", name: "Lee Sin", roles: ["Jungle"] },
  { id: "Leona", name: "Leona", roles: ["Support"] },
  { id: "Lillia", name: "Lillia", roles: ["Jungle"] },
  { id: "Lissandra", name: "Lissandra", roles: ["Mid"] },
  { id: "Lucian", name: "Lucian", roles: ["Bot", "Mid"] },
  { id: "Lulu", name: "Lulu", roles: ["Support"] },
  { id: "Lux", name: "Lux", roles: ["Support", "Mid"] },
  { id: "Malphite", name: "Malphite", roles: ["Top", "Mid", "Support"] },
  { id: "Malzahar", name: "Malzahar", roles: ["Mid"] },
  { id: "Maokai", name: "Maokai", roles: ["Jungle", "Support", "Top"] },
  { id: "MasterYi", name: "Master Yi", roles: ["Jungle"] },
  { id: "Milio", name: "Milio", roles: ["Support"] },
  { id: "MissFortune", name: "Miss Fortune", roles: ["Bot"] },
  { id: "Mordekaiser", name: "Mordekaiser", roles: ["Top", "Jungle"] },
  { id: "Morgana", name: "Morgana", roles: ["Support", "Jungle", "Mid"] },
  { id: "Naafiri", name: "Naafiri", roles: ["Mid"] },
  { id: "Nami", name: "Nami", roles: ["Support"] },
  { id: "Nasus", name: "Nasus", roles: ["Top"] },
  { id: "Nautilus", name: "Nautilus", roles: ["Support"] },
  { id: "Neeko", name: "Neeko", roles: ["Mid", "Support"] },
  { id: "Nidalee", name: "Nidalee", roles: ["Jungle"] },
  { id: "Nilah", name: "Nilah", roles: ["Bot"] },
  { id: "Nocturne", name: "Nocturne", roles: ["Jungle"] },
  { id: "Nunu", name: "Nunu & Willump", roles: ["Jungle"] },
  { id: "Olaf", name: "Olaf", roles: ["Jungle", "Top"] },
  { id: "Orianna", name: "Orianna", roles: ["Mid"] },
  { id: "Ornn", name: "Ornn", roles: ["Top"] },
  { id: "Pantheon", name: "Pantheon", roles: ["Top", "Mid", "Support", "Jungle"] },
  { id: "Poppy", name: "Poppy", roles: ["Top", "Jungle", "Support"] },
  { id: "Pyke", name: "Pyke", roles: ["Support"] },
  { id: "Qiyana", name: "Qiyana", roles: ["Mid", "Jungle"] },
  { id: "Quinn", name: "Quinn", roles: ["Top"] },
  { id: "Rakan", name: "Rakan", roles: ["Support"] },
  { id: "Rammus", name: "Rammus", roles: ["Jungle"] },
  { id: "RekSai", name: "Rek'Sai", roles: ["Jungle"] },
  { id: "Rell", name: "Rell", roles: ["Support", "Jungle"] },
  { id: "Renata", name: "Renata Glasc", roles: ["Support"] },
  { id: "Renekton", name: "Renekton", roles: ["Top"] },
  { id: "Rengar", name: "Rengar", roles: ["Jungle", "Top"] },
  { id: "Riven", name: "Riven", roles: ["Top"] },
  { id: "Rumble", name: "Rumble", roles: ["Top", "Mid", "Jungle"] },
  { id: "Ryze", name: "Ryze", roles: ["Mid", "Top"] },
  { id: "Samira", name: "Samira", roles: ["Bot"] },
  { id: "Sejuani", name: "Sejuani", roles: ["Jungle", "Top"] },
  { id: "Senna", name: "Senna", roles: ["Support", "Bot"] },
  { id: "Seraphine", name: "Seraphine", roles: ["Support", "Mid", "Bot"] },
  { id: "Sett", name: "Sett", roles: ["Top", "Support"] },
  { id: "Shaco", name: "Shaco", roles: ["Jungle", "Support"] },
  { id: "Shen", name: "Shen", roles: ["Top", "Support"] },
  { id: "Shyvana", name: "Shyvana", roles: ["Jungle", "Top"] },
  { id: "Singed", name: "Singed", roles: ["Top"] },
  { id: "Sion", name: "Sion", roles: ["Top"] },
  { id: "Sivir", name: "Sivir", roles: ["Bot"] },
  { id: "Skarner", name: "Skarner", roles: ["Jungle", "Top"] },
  { id: "Smolder", name: "Smolder", roles: ["Bot"] },
  { id: "Sona", name: "Sona", roles: ["Support"] },
  { id: "Soraka", name: "Soraka", roles: ["Support"] },
  { id: "Swain", name: "Swain", roles: ["Support", "Mid", "Top"] },
  { id: "Sylas", name: "Sylas", roles: ["Mid", "Jungle"] },
  { id: "Syndra", name: "Syndra", roles: ["Mid"] },
  { id: "TahmKench", name: "Tahm Kench", roles: ["Support", "Top"] },
  { id: "Taliyah", name: "Taliyah", roles: ["Jungle", "Mid"] },
  { id: "Talon", name: "Talon", roles: ["Mid", "Jungle"] },
  { id: "Taric", name: "Taric", roles: ["Support"] },
  { id: "Teemo", name: "Teemo", roles: ["Top", "Support"] },
  { id: "Thresh", name: "Thresh", roles: ["Support"] },
  { id: "Tristana", name: "Tristana", roles: ["Bot", "Mid"] },
  { id: "Trundle", name: "Trundle", roles: ["Top", "Jungle"] },
  { id: "Tryndamere", name: "Tryndamere", roles: ["Top"] },
  { id: "TwistedFate", name: "Twisted Fate", roles: ["Mid"] },
  { id: "Twitch", name: "Twitch", roles: ["Bot", "Support"] },
  { id: "Udyr", name: "Udyr", roles: ["Jungle", "Top"] },
  { id: "Urgot", name: "Urgot", roles: ["Top"] },
  { id: "Varus", name: "Varus", roles: ["Bot", "Mid"] },
  { id: "Vayne", name: "Vayne", roles: ["Bot", "Top"] },
  { id: "Veigar", name: "Veigar", roles: ["Mid", "Support"] },
  { id: "Velkoz", name: "Vel'Koz", roles: ["Support", "Mid"] },
  { id: "Vex", name: "Vex", roles: ["Mid"] },
  { id: "Vi", name: "Vi", roles: ["Jungle"] },
  { id: "Viego", name: "Viego", roles: ["Jungle"] },
  { id: "Viktor", name: "Viktor", roles: ["Mid"] },
  { id: "Vladimir", name: "Vladimir", roles: ["Mid", "Top"] },
  { id: "Volibear", name: "Volibear", roles: ["Jungle", "Top"] },
  { id: "Warwick", name: "Warwick", roles: ["Jungle", "Top"] },
  { id: "Wukong", name: "Wukong", roles: ["Jungle", "Top"] },
  { id: "Xayah", name: "Xayah", roles: ["Bot"] },
  { id: "Xerath", name: "Xerath", roles: ["Support", "Mid"] },
  { id: "XinZhao", name: "Xin Zhao", roles: ["Jungle"] },
  { id: "Yasuo", name: "Yasuo", roles: ["Mid", "Bot", "Top"] },
  { id: "Yone", name: "Yone", roles: ["Mid", "Top"] },
  { id: "Yorick", name: "Yorick", roles: ["Top"] },
  { id: "Yuumi", name: "Yuumi", roles: ["Support"] },
  { id: "Zac", name: "Zac", roles: ["Jungle", "Top"] },
  { id: "Zed", name: "Zed", roles: ["Mid", "Jungle"] },
  { id: "Zeri", name: "Zeri", roles: ["Bot"] },
  { id: "Ziggs", name: "Ziggs", roles: ["Bot", "Mid"] },
  { id: "Zilean", name: "Zilean", roles: ["Support", "Mid"] },
  { id: "Zoe", name: "Zoe", roles: ["Mid"] },
  { id: "Zyra", name: "Zyra", roles: ["Support", "Jungle"] }
];

export const getChampionImage = (id) => `https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/${id}.png`;
